In [1]:
import pandas as pd
import numpy as np
import json
import warnings
movies = pd.read_csv('input.csv')

In [2]:
movies.head()

,id,original_title,genres,cast,vote_average,crew,keywords
0,206647,Spectre,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...",6.3,"[{""credit_id"": ""54805967c3a36829b5002c41"", ""de...","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name..."
1,49529,John Carter,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...",6.1,"[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de...","[{""id"": 818, ""name"": ""based on novel""}, {""id"":..."
2,559,Spider-Man 3,"[{""id"": 14, ""name"": ""Fantasy""}, {""id"": 28, ""na...","[{""cast_id"": 30, ""character"": ""Peter Parker / ...",5.9,"[{""credit_id"": ""52fe4252c3a36847f80151a5"", ""de...","[{""id"": 851, ""name"": ""dual identity""}, {""id"": ..."
3,38757,Tangled,"[{""id"": 16, ""name"": ""Animation""}, {""id"": 10751...","[{""cast_id"": 34, ""character"": ""Flynn Rider (vo...",7.4,"[{""credit_id"": ""52fe46db9251416c91062101"", ""de...","[{""id"": 1562, ""name"": ""hostage""}, {""id"": 2343,..."
4,99861,Avengers: Age of Ultron,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""cast_id"": 76, ""character"": ""Tony Stark / Ir...",7.3,"[{""credit_id"": ""55d5f7d4c3a3683e7e0016eb"", ""de...","[{""id"": 8828, ""name"": ""marvel comic""}, {""id"": ..."

In [5]:
# Processing data before using model
def change(data):
    
    import pandas as pd
    import numpy as np
    import json
    import warnings
    warnings.filterwarnings('ignore')
    
    data["genres"] = data["genres"].apply(json.loads)
    for index,i in zip(data.index,data["genres"]):
        list1 = []
        for j in range(len(i)):
            list1.append((i[j]['name']))
        data.loc[index,"genres"] = str(list1)


    data["keywords"] = data["keywords"].apply(json.loads)
    for index,i in zip(data.index,data["keywords"]):
        list1 = []
        for j in range(len(i)):
            list1.append((i[j]['name']))
        data.loc[index,"keywords"] = str(list1)


    data["cast"] =  data["cast"].apply(json.loads)
    for index,i in zip( data.index, data["cast"]):
        list1 = []
        for j in range(len(i)):
            list1.append((i[j]['name']))
        data.loc[index,"cast"] = str(list1)

     
    data["crew"] =  data["crew"].apply(json.loads)
    def director(x):
        for i in x:
            if i['job'] == 'Director':
                return i['name']
    data["crew"] =  data["crew"].apply(director)
    
    
    
    
    
    
    data["genres"] = data["genres"].str.strip('[]').str.replace(' ','').str.replace("'",'')
    data["genres"] = data["genres"].str.split(',')
    for i,j in zip(data["genres"],data.index):
        list2=[]
        list2=i
        list2.sort()
        data.loc[j,"genres"]=str(list2)
    data["genres"] = data["genres"].str.strip('[]').str.replace(' ','').str.replace("'",'')
    data["genres"] = data["genres"].str.split(',')
    
    genreList1 = []
    for index, row in data.iterrows():
        genres = row["genres"]

        for genre in genres:
            if (genre!='') & (genre not in genreList1):
                genreList1.append(genre)
                
                
    def binary(genre_list):
        binaryList1 = []
        for genre in genreList1:
            if genre in genre_list:
                binaryList1.append(1)
            else:
                binaryList1.append(0)
        return binaryList1
    data["genres"]=data["genres"].apply(lambda x: binary(x))
    
    
    
    data["keywords"] = data["keywords"].str.strip('[]').str.replace(' ','').str.replace("'",'')
    data["keywords"] = data["keywords"].str.split(',')
    for i,j in zip(data["keywords"],data.index):
        list2=[]
        list2=i
        list2.sort()
        data.loc[j,"keywords"]=str(list2)
    data["keywords"] = data["keywords"].str.strip('[]').str.replace(' ','').str.replace("'",'')
    data["keywords"] = data["keywords"].str.split(',')
    
    genreList2 = []
    for index, row in data.iterrows():
        genres = row["keywords"]

        for genre in genres:
            if (genre!='') & (genre not in genreList2):
                genreList2.append(genre)
    def binary(genre_list):
        binaryList2 = []
        for genre in genreList2:
            if genre in genre_list:
                binaryList2.append(1)
            else:
                binaryList2.append(0)
        return binaryList2
    data["keywords"]=data["keywords"].apply(lambda x: binary(x))
    
    
    
    data["cast"] = data["cast"].str.strip('[]').str.replace(' ','').str.replace("'",'')
    data["cast"] = data["cast"].str.split(',')
    for i,j in zip(data["cast"],data.index):
        list2=[]
        list2=i[:4]
        list2.sort()
        data.loc[j,"cast"]=str(list2)
    data["cast"] = data["cast"].str.strip('[]').str.replace(' ','').str.replace("'",'')
    data["cast"] = data["cast"].str.split(',')
    
    genreList3 = []
    for index, row in data.iterrows():
        genres = row["cast"]

        for genre in genres:
            if (genre!='') & (genre not in genreList3):
                genreList3.append(genre)
    def binary(genre_list):
        binaryList3 = []
        for genre in genreList3:
            if genre in genre_list:
                binaryList3.append(1)
            else:
                binaryList3.append(0)
        return binaryList3
    data["cast"]=data["cast"].apply(lambda x: binary(x))
    
    
    
    def xstr(s):
        if s is None:
            return ''
        return str(s)
    data["crew"] = data["crew"].apply(xstr)
    
    genreList4=[]
    for i in data["crew"]:
        if i not in genreList4:
            genreList4.append(i)
    def binary(genre_list):
        binaryList4 = []
        for genre in genreList4:
            if genre in genre_list:
                binaryList4.append(1)
            else:
                binaryList4.append(0)
        return binaryList4
    data["crew"]=data["crew"].apply(lambda x: binary(x))
    data['id']=list(range(0,movies.shape[0]))
    return(data)

In [6]:
change(df)

,id,original_title,genres,cast,vote_average,crew,keywords
0,0,Spectre,"[1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0]","[1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",6.3,"[1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]","[1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, ..."
1,1,John Carter,"[1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0]","[0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, ...",6.1,"[0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]","[1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, ..."
2,2,Spider-Man 3,"[1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0]","[0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, ...",5.9,"[0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]","[0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
3,3,Tangled,"[0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0]","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, ...",7.4,"[0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
4,4,Avengers: Age of Ultron,"[1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0]","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",7.3,"[0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]","[0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, ..."
5,5,Superman Returns,"[1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0]","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",5.4,"[0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0]","[0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
6,6,Quantum of Solace,"[1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0]","[0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",6.1,"[0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0]","[0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
7,7,The Avengers,"[1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0]","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",7.4,"[0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
8,8,Captain America: Civil War,"[1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0]","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",7.1,"[0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0]","[0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, ..."
9,9,Skyfall,"[1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0]","[0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",6.9,"[1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]","[0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
10,10,Spider-Man 2,"[1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0]","[0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, ...",6.7,"[0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]","[0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
11,11,Oz: The Great and Powerful,"[0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0]","[0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, ...",5.7,"[0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]","[0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, ..."
12,12,World War Z,"[1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0]","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",6.7,"[0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0]","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
13,13,X-Men: Days of Future Past,"[1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0]","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",7.5,"[0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0]","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
14,14,Spider-Man,"[1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0]","[0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, ...",6.8,"[0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
15,15,X2,"[1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0]","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",6.8,"[0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0]","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
16,16,Home on the Range,"[0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0]","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",5.7,"[0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0]","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
17,17,Terminator 2: Judgment Day,"[1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0]","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",7.7,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0]","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
18,18,Divergent,"[1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0]","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",6.9,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0]","[1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
19,19,Road to Perdition,"[0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0]","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",7.3,"[1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
20,20,X-Men,"[1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0]","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",6.8,"[0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0]","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
21,21,The Angry Birds Movie,"[0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0]","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",5.9,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0]","[0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, ..."
22,22,The Abyss,"[1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0]","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",7.1,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0]","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
23,23,Into the Blue,"[1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0]","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",5.8,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0]","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
24,24,A Bug's Life,"[0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0]","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",6.8,"[0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
25,25,Dune,"[1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0]","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",6.5,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0]","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
26,26,Revolutionary Road,"[0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1]","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",6.7,"[1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
27,27,Serenity,"[1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0]","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",7.4,"[0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
28,28,Machine Gun Preacher,"[1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0]","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",6.4,"[0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0]","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
29,29,Alpha and Omega,"[0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0]","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",5.3,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
30,30,The Terminator,"[1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0]","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",7.3,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0]","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."

In [25]:
d=df[df['original_title'].str.contains('X-Men')].iloc[0].to_frame().T

In [26]:
d['id'].values[0]

13

In [222]:
# recomendation model
def predict_score():
    
    name = input('Enter a movie title: ')
    
    import pandas as pd
    import numpy as np
    import json
    import warnings
    warnings.filterwarnings('ignore')
    from scipy import spatial
    import operator
    
    
    def Similarity(movieId1, movieId2):
        a = movies.iloc[movieId1]
        b = movies.iloc[movieId2]

        genresA = a['genres']
        genresB = b['genres']

        genreDistance = spatial.distance.cosine(genresA, genresB)

        scoreA = a['cast']
        scoreB = b['cast']
        scoreDistance = spatial.distance.cosine(scoreA, scoreB)

        directA = a['crew']
        directB = b['crew']
        directDistance = spatial.distance.cosine(directA, directB)

        wordsA = a['keywords']
        wordsB = b['keywords']
        wordsDistance = spatial.distance.cosine(directA, directB)
        dis=genreDistance + directDistance + scoreDistance + wordsDistance
        return(round(dis,3))
    
    
    
    
    new_movie = movies[movies['original_title'].str.contains(name)].iloc[0].to_frame().T
    def getNeighbors(baseMovie, K):
        distances = []
        for index, movie in movies.iterrows():
            if movie['id'] != baseMovie['id'].values[0]:
                dist = Similarity(baseMovie['id'].values[0], movie['id'])
                distances.append((movie['id'], dist))    
        distances.sort(key=operator.itemgetter(1))
        neighbors = []      
        for x in range(K):
            neighbors.append(distances[x])
        return neighbors
    K = 3
    neighbors = getNeighbors(new_movie, K)
    for neighbor in neighbors:
        s=movies.iloc[neighbor[0]][1]
        print(s)

In [223]:
predict_score()

Enter a movie title:  The Godfather: Part III

The Godfather: Part II
The Godfather
The Rainmaker

In [115]:
import pandas as pd
import numpy as np
credits = pd.read_csv('credits.csv')
movies = pd.read_csv('movies.csv')

In [116]:
movies.head()

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2015-10-26,880674609,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-07-16,1084939099,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-03-07,284139100,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124

In [117]:
movies = movies.merge(credits,on='title')

In [118]:
import json
import ast
ast.literal_eval

In [119]:
movies['genres'] = movies['genres'].apply(json.loads)
for index,i in zip(movies.index,movies['genres']):
    list1 = []
    for j in range(len(i)):
        list1.append((i[j]['name'])) 
    movies.loc[index,'genres'] = str(list1)

In [120]:
movies['keywords'] = movies['keywords'].apply(json.loads)
for index,i in zip(movies.index,movies['keywords']):
    list1 = []
    for j in range(len(i)):
        list1.append((i[j]['name']))
    movies.loc[index,'keywords'] = str(list1)

In [121]:
movies['cast'] = movies['cast'].apply(json.loads)
for index,i in zip(movies.index,movies['cast']):
    list1 = []
    for j in range(len(i)):
        list1.append((i[j]['name']))
    movies.loc[index,'cast'] = str(list1)

In [122]:
movies['crew'] = movies['crew'].apply(json.loads)
def director(x):
    for i in x:
        if i['job'] == 'Director':
            return i['name']
movies['crew'] = movies['crew'].apply(director)
movies.rename(columns={'crew':'director'},inplace=True)

In [123]:
movies.head()

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,movie_id,cast,director
0,237000000,"['Action', 'Adventure', 'Fantasy', 'Science Fi...",http://www.avatarmovie.com/,19995,"['culture clash', 'future', 'space war', 'spac...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",...,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,19995,"['Sam Worthington', 'Zoe Saldana', 'Sigourney ...",James Cameron
1,300000000,"['Adventure', 'Fantasy', 'Action']",http://disney.go.com/disneypictures/pirates/,285,"['ocean', 'drug abuse', 'exotic island', 'east...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...",...,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500,285,"['Johnny Depp', 'Orlando Bloom', 'Keira Knight...",Gore Verbinski
2,245000000,"['Action', 'Adventure', 'Crime']",http://www.sonypictures.com/movies/spectre/,206647,"['spy', 'based on novel', 'secret agent', 'seq...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...",...,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466,206647,"['Daniel Craig', 'Christoph Waltz', 'Léa Seydo...",Sam Mendes
3,250000000,"['Action', 'Crime', 'Drama', 'Thriller']",http://www.thedarkknightrises.com/,49026,"['dc comics', 'crime fighter', 'terrorist', 's...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...",...,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106,49026,"['Christian Bale', 'Michael Caine', 'Gary Oldm...",Christopher Nolan
4,260000000,"['Action', 'Adventure', 'Science Fiction']",http://movies.disney.com/john-carter,49529,"['based on novel', 'mars', 'medallion', 'space...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]",...,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124,49529,"['Taylor Kitsch', 'Lynn Collins', 'Samantha Mo...",Andrew Stanton

In [124]:
movies =movies[['id','original_title','genres','cast','director','vote_average','keywords']]

In [125]:
movies.head()

,id,original_title,genres,cast,director,vote_average,keywords
0,19995,Avatar,"['Action', 'Adventure', 'Fantasy', 'Science Fi...","['Sam Worthington', 'Zoe Saldana', 'Sigourney ...",James Cameron,7.2,"['culture clash', 'future', 'space war', 'spac..."
1,285,Pirates of the Caribbean: At World's End,"['Adventure', 'Fantasy', 'Action']","['Johnny Depp', 'Orlando Bloom', 'Keira Knight...",Gore Verbinski,6.9,"['ocean', 'drug abuse', 'exotic island', 'east..."
2,206647,Spectre,"['Action', 'Adventure', 'Crime']","['Daniel Craig', 'Christoph Waltz', 'Léa Seydo...",Sam Mendes,6.3,"['spy', 'based on novel', 'secret agent', 'seq..."
3,49026,The Dark Knight Rises,"['Action', 'Crime', 'Drama', 'Thriller']","['Christian Bale', 'Michael Caine', 'Gary Oldm...",Christopher Nolan,7.6,"['dc comics', 'crime fighter', 'terrorist', 's..."
4,49529,John Carter,"['Action', 'Adventure', 'Science Fiction']","['Taylor Kitsch', 'Lynn Collins', 'Samantha Mo...",Andrew Stanton,6.1,"['based on novel', 'mars', 'medallion', 'space..."

In [126]:
movies.dropna(inplace=True)

In [127]:
movies['genres'] = movies['genres'].str.strip('[]').str.replace(' ','').str.replace("'",'')
movies['genres'] = movies['genres'].str.split(',')

In [128]:
movies['cast'] = movies['cast'].str.strip('[]').str.replace(' ','').str.replace("'",'').str.replace('"','')
movies['cast'] = movies['cast'].str.split(',')

In [129]:
def space(col):
  if col is None:
    return ' '
  return str(col)

In [130]:
movies['director'] = movies['director'].apply(space)

In [131]:
def features(x):
    return ' '.join(x['keywords']) + ' ' + ' '.join(x['cast']) + ' ' + x['director'] + ' ' + ' '.join(x['genres'])

movies['combine_feature'] = movies.apply(features,axis=1)

In [132]:
movies[['original_title','combine_feature']]

,original_title,combine_feature
0,Avatar,"[ ' c u l t u r e c l a s h ' , ' f u t u ..."
1,Pirates of the Caribbean: At World's End,"[ ' o c e a n ' , ' d r u g a b u s e ' , ..."
2,Spectre,"[ ' s p y ' , ' b a s e d o n n o v e l ..."
3,The Dark Knight Rises,"[ ' d c c o m i c s ' , ' c r i m e f i ..."
4,John Carter,"[ ' b a s e d o n n o v e l ' , ' m a r ..."
...,...,...
4804,El Mariachi,[ ' u n i t e d s t a t e s – m e x i c o ...
4805,Newlyweds,[ ] EdwardBurns KerryBishé MarshaDietlein Cait...
4806,"Signed, Sealed, Delivered","[ ' d a t e ' , ' l o v e a t f i r s t ..."
4807,Shanghai Calling,[ ] DanielHenney ElizaCoupe BillPaxton AlanRuc...
4808,My Date with Drew,"[ ' o b s e s s i o n ' , ' c a m c o r d e ..."

In [133]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics.pairwise import cosine_similarity
cv = CountVectorizer(stop_words='english') 
count_matrix = cv.fit_transform(movies["combine_feature"]) 
cosine_sin = cosine_similarity(count_matrix,count_matrix)
movies = movies.reset_index()
indices = pd.Series(movies.index, index = movies['original_title'])

In [134]:
def movies_recommendations(title, cosine_sim=cosine_sin):
    idx = indices[title]
    sim_scores = list(enumerate(cosine_sim[idx]))
    sim_scores = sorted(sim_scores, key=lambda x: x[1], reverse=True)
    sim_scores = sim_scores[1:11]
    movie_indices = [i[0] for i in sim_scores]
    return(pd.DataFrame({'Movie':list(movies.loc[movie_indices,'original_title'])}))

In [137]:
movies_recommendations('Shanghai Calling')

                     Movie
0                  Twister
1              Dawn Patrol
2  Everything Put Together
3                  三国之见龙卸甲
4   Breakin' All the Rules
5    Supporting Characters
6        The Last Exorcism
7            The Naked Ape
8                True Lies
9            A Simple Plan

In [61]:
movies

,index,id,original_title,genres,cast,director,vote_average,keywords,combine_feature
0,0,19995,Avatar,"[Action, Adventure, Fantasy, ScienceFiction]","[SamWorthington, ZoeSaldana, SigourneyWeaver, ...",James Cameron,7.2,"['culture clash', 'future', 'space war', 'spac...","[ ' c u l t u r e c l a s h ' , ' f u t u ..."
1,1,285,Pirates of the Caribbean: At World's End,"[Adventure, Fantasy, Action]","[JohnnyDepp, OrlandoBloom, KeiraKnightley, Ste...",Gore Verbinski,6.9,"['ocean', 'drug abuse', 'exotic island', 'east...","[ ' o c e a n ' , ' d r u g a b u s e ' , ..."
2,2,206647,Spectre,"[Action, Adventure, Crime]","[DanielCraig, ChristophWaltz, LéaSeydoux, Ralp...",Sam Mendes,6.3,"['spy', 'based on novel', 'secret agent', 'seq...","[ ' s p y ' , ' b a s e d o n n o v e l ..."
3,3,49026,The Dark Knight Rises,"[Action, Crime, Drama, Thriller]","[ChristianBale, MichaelCaine, GaryOldman, Anne...",Christopher Nolan,7.6,"['dc comics', 'crime fighter', 'terrorist', 's...","[ ' d c c o m i c s ' , ' c r i m e f i ..."
4,4,49529,John Carter,"[Action, Adventure, ScienceFiction]","[TaylorKitsch, LynnCollins, SamanthaMorton, Wi...",Andrew Stanton,6.1,"['based on novel', 'mars', 'medallion', 'space...","[ ' b a s e d o n n o v e l ' , ' m a r ..."
...,...,...,...,...,...,...,...,...,...
4774,4804,9367,El Mariachi,"[Action, Crime, Thriller]","[CarlosGallardo, JaimedeHoyos, PeterMarquardt,...",Robert Rodriguez,6.6,"['united states–mexico barrier', 'legs', 'arms...",[ ' u n i t e d s t a t e s – m e x i c o ...
4775,4805,72766,Newlyweds,"[Comedy, Romance]","[EdwardBurns, KerryBishé, MarshaDietlein, Cait...",Edward Burns,5.9,[],[ ] EdwardBurns KerryBishé MarshaDietlein Cait...
4776,4806,231617,"Signed, Sealed, Delivered","[Comedy, Drama, Romance, TVMovie]","[EricMabius, KristinBooth, CrystalLowe, GeoffG...",Scott Smith,7.0,"['date', 'love at first sight', 'narration', '...","[ ' d a t e ' , ' l o v e a t f i r s t ..."
4777,4807,126186,Shanghai Calling,[],"[DanielHenney, ElizaCoupe, BillPaxton, AlanRuc...",Daniel Hsia,5.7,[],[ ] DanielHenney ElizaCoupe BillPaxton AlanRuc...
4778,4808,25975,My Date with Drew,[Documentary],"[DrewBarrymore, BrianHerzlinger, CoreyFeldman,...",Brian Herzlinger,6.3,"['obsession', 'camcorder', 'crush', 'dream girl']","[ ' o b s e s s i o n ' , ' c a m c o r d e ..."

In [94]:
movies.loc[1,'cast']

['JohnnyDepp',
 'OrlandoBloom',
 'KeiraKnightley',
 'StellanSkarsgård',
 'ChowYun-fat',
 'BillNighy',
 'GeoffreyRush',
 'JackDavenport',
 'KevinMcNally',
 'TomHollander',
 'NaomieHarris',
 'JonathanPryce',
 'KeithRichards',
 'LeeArenberg',
 'MackenzieCrook',
 'GregEllis',
 'DavidBailie',
 'MartinKlebba',
 'DavidSchofield',
 'LaurenMaher',
 'VanessaBranch',
 'AngusBarnett',
 'GilesNew',
 'ReggieLee',
 'DominicScottKay',
 'TakayoFischer',
 'DavidMeunier',
 'Ho-KwanTse',
 'AndyBeckwith',
 'PeterDonaldBadalamentiII',
 'ChristopherS.Capp',
 'KeithRichards',
 'HakeemKae-Kazim',
 'GhassanMassoud']